version: '3.1'

services:

  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: springbatchpocdb
      MYSQL_ROOT_PASSWORD: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080